campaign = input('Hello adventurer! Welcome to your campaign. Is this your first time? Respond with YES or NO: ')
if campaign.lower() == 'yes':
    print('Oh how exciting! I hope you are able to learn a lot about adventuring through this campaign as it is your first time! Ask all the questions you need along your journey. Well, for this campaign, you will be responding to each option with the word or phrase in ALL CAPS you desire to follow. Please choose carefully!')
elif campaign.lower() == 'no':
    print('Well how about that! An old adventurer! I hope you are ready to learn a lot through this campaign, though you may even be able to teach me a thing or two. Well, for this campaign, you will be responding to each option with the word or phrase in ALL CAPS you desire to follow. Please choose carefully!')
else:
    print(f'Hmm. Odd answer. I asked a yes or no question and you responded with "{campaign.lower()}"! Well, for this campaign, you will be responding to each option with the word or phrase in ALL CAPS you desire to follow. Please choose carefully!')
interaction = input('Our story starts in a small village. You are an adventurer in a world where many odd things happen everyday. Raging beasts are plenty causing food to become scarce as they take livestock and destroy fields. With the world swirling into chaos, you are left to head out on an adventure to earn money so you can feed yourself. You head to the tavern and see two people who could help you find something worth doing. Do you talk to the BARTENDER, or ADVENTURER?: ')
if interaction.lower() == 'adventurer':
    adventurer = input('You walk to the adventurer with confidence. Surely he will know what to do! With a swift introduction, you are quick to ask the adventurer if he knows any campaigns you can go on to earn money. "Why, sure I do kid! In face, I am looking for a mighty team to go on a campaign. Would you like to join us?" He asks in a rough voice. Do you JOIN, or ASK FOR BOUNTY?: ')
    if adventurer.lower() == 'join':
        join = input('"I would like to join. What is the campaign?" You blurt out. The adventurer widens his eyes a bit in shock before letting out a loud laugh. "I am impressed with your courage, young adventurer! Well, the campaign is to fight a dragon. We better head off now though." The adventurer says as he gets up. He proceeds to drag you out of the tavern to meet his team. When you both get to his camp, you are met with a well-rounded team of adventurers. A variety of new and old adventurers with different skills greet you in their own unique ways. As the day shifts into night, you are conflicted on what you want to do. Part of you wants to run from this battle and the other feels confident enough to continue with the team that was made by the leader. Do you RUN, or CONTINUE?: ')
        if join.lower() == 'run':
            adventurer_run = input('The nagging feeling of running eats at you until you are no longer able to stand it. Once the team is asleep, you sneak away from camp and start to run through the unknown woods. After some time, you trip on a branch and fall down a hill into a camp of bandits. The bandits jump up with weapons drawn, all pointed at you. "What brings you here?!" A booming voice vibrates through your chest. You look up to meet eyes with what appears to be the captain of the bandits. "I am deeply sorry, I stumbled upon your camp by tripping over a branch and falling down the hill. I mean no harm, truly." The bandits look up to their captain and one whispers into his ear. You notice their gazes lead to your arsenal strapped around your waist. "It looks like you are a skilled fighter, is that so?" Asks the captain of the bandits. A quick nod from your head sends worry into the eyes of some of the bandits, while some have a glimer of hope in their eyes. "How about you join us? We need a strong person like you with us." Do you JOIN or RUN?: ')
            if adventurer_run.lower() == 'join':
                print('"Will I be supplied with money and food if I join?" Hope filling your chest. You only set out to find money or food from the start anyway, so you are desperate for either. "Yes, plenty of food and money is provided to all of our members. We divide our plunders evenly so we are all fed. Then we train those who are weak and train those who are strong, so we may succeed even more." A smile forms across your face. You shake hands with the captain and live the rest of your days as a bandit, living life always on the verge of not having enough money or food to live. The end.')
            elif adventurer_run.lower() == 'run':
                print('Quickly, you start to run from the bandits. They shoot arrows at you and some attempt to hit you with their swords, but you manage to escape. Eventually, you stumble upon a newly abandoned farm. The house is full of dust and most of the crops are dead, but there is hope for a new beginning. With your ability to quickly adapt, you soon pick up the skills to build, farm and tend to livestock. You live the rest of your life fending off bandits and growing your farm, becoming fully self-sustaining. The end.')
            else:
                print('Invalid answer. Please start your quest again and answer according to the options available. I hope to see you again, adventurer.')
        elif join.lower() == 'continue':
            adventurer_continue = input('You push aside the feeling to run and continue your journey with your new found team. As you journey with the team, you are quick to form close relationships with each of the members resulting in some of them being able to teach you magic. After a few months of your journey, you are able to cast some basic spells and some attack spells, but you lack the confidence in your abilities to cast more powerful spells. The day arrives when you have made it to the lair of the dragon. A battle quickly starts when the dragon spots all of you approaching. One by one, your team is becoming smaller as each person is rendered unable to fit or tragically dies. You also start to run out of weapons, soon approaching your demise if you are unable to defend yourself. With one arrow left to use with your bow, you are left to decide if you are going to attempt to use your newly learned magic. Do you SHOOT, or use MAGIC?: ')
            if adventurer_continue.lower() == 'shoot':
                print('You decide to shoot your last arrow at the dragon, who is turned facing the adventurer on the opposite side of the battlefield. With the release from your bow, the arrow flies and is launched into the back of the neck of the dragon. The scales of the dragon prevent the arrow from drawing blood, but instead causes the dragon to focus on you. With no time to use magic or any weapons left to defend yourself, the dragon swiftly kicks back at you, ending your life in one blow. You, along with all your fellow team mates who passed away that day, are remembered as heros who gave their lives to end the terrors of the dragon. The adventurer who managed to survive brings flowers to your grave often, never forgetting the young adventurer who risked their life to protect him in the end.')
            elif adventurer_continue.lower() == 'magic':
                print('With a few moments to gather your magic as the dragon faces the adventurer, you decided to gather up as much confidence and strength to unleash the most powerful spell you could cast. As the dragon raises its hand to slash the adventurer, you finish your spell and slay the dragon. The adventurer survives and is impressed with the magic you were able to cast to protect him. You, along with the rest of the surviving team members and the adventurer, make your way to the Star Kingdom, which you had learned commissioned the bounty. Though you decide to not tell your story, the adventurer is quick to boast to the Queen and King about your bravery. From that day on, you are celebrated as a hero who came from nothing. Plenty of money and food fill the rest of your days, but you always made sure to give as much as possible to the needy because you understand the lives they are living. The end.')
            else:
                print('Invalid answer. Please start your quest again and answer according to the options available. I hope to see you again, adventurer.')
        else:
             print('Invalid answer. Please start your quest again and answer according to the options available. I hope to see you again, adventurer.')
    elif adventurer.lower() == 'ask for bounty':
        bounty = input('"No thanks, sir. I would like to go on a campaign alone. Do you know of any campaigns I can do?" You ask confident in yourself. Though you have not done much as a solo adventurer, you are sure there is something you can do.He shrugs his shoulders and sighs, clearly disappointed he missed the opportunity to gain a new team member. "There is one bounty I know of that you can do. There is a thief running wild nearby. Nobody has been able to catch a glimpse of whoever the thief is, so it will be hard to track down the thief." Do you ACCEPT, or DENY the bounty?: ')
        if bounty.lower() == 'accept':
            accept = input('"I think I will be able to handle that." You say as you take the poster with the bounty details from the adventurer. "Thank you, sir!" You say as you stride out of the tavern. Heading in the direction of the bounty, you come up with a plan to capture the thief. If you have learned anything from dealing with thieves, you know they will always go for a large sum of money that is left unattended. Once you arrive, you set up for the thief. You hide near the "unattended" sum of money and wait. After a few hours, you finally catch the thief in your trap. Though upon closer examination you soon realize the thief is a young boy who appears to be starving. You are faced with having mercy on the child by taking care of it or bringing justice. Do you have MERCY, or bring JUSTICE?: ')
            if accept.lower() == 'mercy':
                print('With sympathy for the child and understanding what he must be living through, you decide to talk to him. "Hey kid, I know we have gotten off on the wrong foot, but I want to take care of you. I understand why you are stealing, but let me show you how to earn money instead of stealing, okay? I will feed you and teach you until you can survive on your own because I do not want to put you in jail." He looks up at you and agrees to being taken care of by you. You take the child away from the city and set up a camp for the two of you. The sun sets and you decide to put him to bed. When sleep takes over, you relax in your tent and feel at peace with what you are doing. Upon waking up, a sense of dread washes over you though. You sit up and realize all of your valuables are missing along with the child. Frustration washes over you as you are unable to find the child again over the next few months. Eventually you give up on finding him and move on with revenge set in your heart. The end.')
            elif accept.lower() == 'justice':
                print('Though you feel sympathy for the child, you feel sympathy for the people he has stolen from as well. The best thing you can do for yourself and everyone besides this child is to bring him in for the bounty. The child does not fight against you as you bring him to the town leader. With the payment from the bounty, you watch as the child is put on trial and is sentenced for his crimes. Maybe in the future he will grow up to be a better person. The end.')
            else:
                print('Invalid answer. Please start your quest again and answer according to the options available. I hope to see you again, adventurer.')
        elif bounty.lower() == 'deny':
            deny = input('"Uh, is there anything else available?" You ask the adventurer. With a shake of his head, you realize you only have one option left and that is to join his team. "Then I will join your team. I need to do something and that sounds better than that bounty." The adventurer smirks and brings you along to meet the well rounded team he has made. The decision you made does not sit right with you though. Thoughts run through your head as you try to decide what you might do instead. Only two options seem possible now. Stealing from the team or staying. Do you STEAL, or STAY?: ')
            if deny.lower() == 'steal':
                print('Deciding to steal from the team, you wait until everyone is asleep. Once you have successfully taken many valuable items, you escape as quietly as possible to avoid waking anyone and getting caught. You find a town after a while of wandering. Upon entering the town you spot a lone child, thin and eyeing you. You decide to share some of what you stole so the child has some money he will be able to earn and buy food with. The end.')
            elif deny.lower() == 'stay':
                print('You decide to do what is right and stay with the team. Eventually you and your team work through many campaigns, earning large amounts of money and fame. You have been able to make a name for yourself as a hero and you live the rest of your life enjoying the campaigns you do. Eventually you replace the adventurer as the leader until you find your successor. The end.')
            else:
                print('Invalid answer. Please start your quest again and answer according to the options available. I hope to see you again, adventurer.')
        else:
            print('Invalid answer. Please start your quest again and answer according to the options available. I hope to see you again, adventurer.')
    else:
        print('Invalid answer. Please start your quest again and answer according to the options available. I hope to see you again, adventurer')
elif interaction.lower() == 'bartender':
    bartender = input('The bartender deals with a lot of people everyday. Maybe he knows a thing or two about how to earn money. You make your way to the bar and wait for him to come to you as he rushes to deal with other customers. "How can I help you kid? You look too young to be up here." He says with a certain annoyance he has gained over the years towards kids. "Do you know what I can do to earn money, maybe like a campaign of sorts?" Words just spill out of your mouth. You are eager to earn money. "I do not, but I can either give you a map some adventurer left behind or give you directions to a campaign I heard is happening nearby. What do you say?" Do you take the MAP, or ask for DIRECTIONS?: ')
    if bartender.lower() == 'map':
        map = input('"The map sounds just fine for me." You breathe out. He turns his back to you and grabs for the map he had laying on a shelf. "Here you go kid. Make sure to make it back alive. I have no clue what campaigns are marked on this map." After a quick glance at the map, you decide to follow the campaign listed as the "three perilous trails" that falls just at the edge of the map, making it impossible to see what comes from each trail. After adventuring for what feels like months, you finally make it to the three trails. One is labeled "Fire", the trail looking as if it is full of burnt trees. The second is labeled "Ice", the trail containing trees that look like they are forever bound to Winter. The final and third is labeled "Wind", with trees that look like they have experienced long lives of harsh winds. Do you go down trail FIRE, ICE, EARTH, or WIND?: ')
        if map.lower() == 'fire':
            print('You choose to go down the path with the burnt trees. Danger signs are nailed again many dead trees, but none of the warnings say what danger lies ahead. You press forward, but are met with the same fate all adventurers have when they go down the same trail. A pit open up underneath you, the earth swallowing you and dropping you into a pool of lava. Your adventure has come to a tragic end.')
        elif map.lower() == 'ice':
            ice = input('The path labeled "Ice" is your choice. Without considering why the trees look to be forever bound to Winter, you walk down the path without Winter clothes. Eventually, cold wind and snow bite at your skin. You are left freezing, but when all seems lost you spot a house up ahead. From the outside, you do not see any lights on. Do you BREAK IN, or KNOCK?: ')
            if ice.lower() == 'break in':
                print('With all the strength you have left, you break the front door down. You find some wood and start making a fire in the firepit. As you start to warm up from the fire you set up, you hear heavy footsteps stomping up some stairs. Quickly, you realize there was a basement to this house you were not aware of. A large figure walks up to you, rage fills his eyes as he stares at you. Quickly you realize he is the adventurer from the tavern you decided not to talk to. With axe in hand, he spares no time to allow you to talk as he swings it at you. The cold infested in your body does not allow you to move, so you are struck dead. If only you had knocked is the last thing you think of as your soul leaves your body.')
            elif ice.lower() == 'knock':
                print('Though you want to get out of the cold quickly, you know how dangerous it can be if you just break in. Hoping someone is home, you quickly knock on the door. Relief washes over you as you hear people inside coming to the door. When the door opens you are shocked to see that the adventurer from the tavern owns the house. Shaking that feeling off, you ask for refuge from the cold. He lets you in and you explain what happened to you as his team of adventurers work to warm you up with a fire and a warm drink of your choice. To repay the kindness of the adventurer and his team, you offer to work for them. The adventurer agrees and you go on to live a life of battle. Victory starts to come easy to you and your team as you learn about each other. Eventually your team is recognized as heroes across the land and you live an exciting, fulfilling life. The end.')
            else:
                print('Invalid answer. Please start your quest again and answer according to the options available. I hope to see you again, adventurer.')
        elif map.lower() == 'wind':
            wind = input('Fighting against the wind, you start your journey down the trail labeled "Wind". After what feels like forever walking against the wind, it suddenly becomes stronger. You look ahead of you to find a maiden in trouble. A large beast made of swirling wind has taken her captive. The maiden sees you and calls out for help. Do you HELP, or RUN?: ')
            if wind.lower() == 'help':
                print('Quickly, you rush forward to fight the beast. After a long battle, you finally succeed at getting the maiden free. You soon realize that she is the princess of the Star Kingdom. She brings you to her kingdom to reward you for your heroic acts. You are praised as a hero and given a job as the guard of the princess, who eventually becomes Queen. The end.')
            elif wind.lower() == 'run':
                print('You turn and run from the scene before you. As you run, you hear the maiden yell "You will regret the day you run from helping me! I promise that!". Ignoring her attempts of making you help, you continue to run. After a few months, you realize the maiden that day was the princess of the Star Kingdom and after being saved by someone else she has put out a bounty for you. You live the rest of your life hiding from everyone until your capture. Then you are thrown into a jail cell to never see freedom again. The end.')
            else:
                print('Invalid answer. Please start your quest again and answer according to the options available. I hope to see you again, adventurer.')
        elif map.lower() == 'earth':
            print('Trick question! There is no "Earth" trail! Only three trails are available to explore. Go back and try again, but go down one of the actual trails! Enjoy your adventure.')
        else:
            print('Invalid answer. Please start your quest again and answer according to the options available. I hope to see you again, adventurer.')
    elif bartender.lower() == 'directions':
        directions = input('"Can I get some directions then?" You ask, hoping he gives you good directions. After a quick conversation you feel confident he gave you good directions, but as you start on your journey and end up in a new town, you are not sure where you are. In fact, you are lost! You see two people nearby you could talk to. Do you talk to the TOWNSPERSON, or FARMHAND?: ')
        if directions.lower() == 'farmhand':
            farmhand = input('You walk up to the farmhand. "Excuse me, but can you help me with directions? I seem to be lost." You ask as the farmhand turns towards you. "I am sorry, but I do not know how to give directions. I was never sent to school because my parents expected me to do what I am doing. Do you need anything else?" He says with a smile. You give a sigh and your stomach grumbles loud enough for him to hear. "Oh! Are you needing food?" "Yes, actually. That is why I am trying to go on a campaign, to earn money to buy some food for myself." His eyes light up as an idea comes to mind. "Well, we need some more hands around here. How about you come work for us and we will feed ya. What do you say?" Do you ACCEPT, or DECLINE?: ')
            if farmhand.lower() == 'decline':
                print('"No, thanks. I will be on my way then. Thank you." You turn and start heading in the way you believe is correct. There is nobody in sight anymore in the town, so you continue on only to become a lost wanderer. You were never good at directions without a map, leaving you to live the rest of your life wandering from city to city in hopes to find a place you know. The end.')
            elif farmhand.lower() == 'accept':
                print('"Sure. What do I need to do?" Quickly you learn how to run a farm. The food you are given is okay, so you decide to learn how to cook on your own through trial and error with leftover supplies. Eventually you are cooking for the farm and you enjoy the rest of your life by fending off beasts from the fields and livestock.')
            else:
                print('Invalid answer. Please start your quest again and answer according to the options available. I hope to see you again, adventurer.')
        elif directions.lower() == 'townsperson':
            townsperson = input('You stride towards the townsperson. "Excuse me, can you help me? I seem to be lost." The townsperson looks at you annoyed. With a roll of his eyes, he turns and says "Did that bartender over yonder give you directions?" A little taken back, you tell him about the directions you got from the bartender. A look of anger spreads across his face. "Oh geez! That bartender is sending you to die!! Listen here kid, that campaign he sent you on has killed far too many people already. I know the directions like the back of my own hand, but I will not tell them to you unless you are completely sure you want to go." Do you GO for the campaign, or LEAVE it?: ')
            if townsperson.lower() == 'go':
                print('"I am sure I want to do the campaign. Please give me the directions." You say eager to try to be the first one to succeed at this campaign. Through another conversation, you are given the directions on paper to help you remember them later on. Eventually you come across the battlefield. Piles of bones line the walls, sending a shiver down your spine. A dragon appears, fierce and angry from having too many people bother it. Without a second to think, the dragon sends you flying into the wall. The life is shocked out of your body upon impact. The end.')
            elif townsperson.lower() == 'leave':
                print('"What?! Well then, I am out of here!" You exlaim, upset with the bartender giving you a deadly campaign. You go back home and find someone else to give you a different campaign. Going along with the new, calmer campaign, you make enough money to support your needs until the next campaign. You live the rest of your life living from campaign to campaign, unable to get bigger commissions due to the lack of experience you have. The end.')
            else:
                print('Invalid answer. Please start your quest again and answer according to the options available. I hope to see you again, adventurer.')
        else:
            print('Invalid answer. Please start your quest again and answer according to the options available. I hope to see you again, adventurer.')
    else:
        print('Invalid answer. Please start your quest again and answer according to the options available. I hope to see you again, adventurer.')
else:
    print('Invalid answer. Please start your quest again and answer according to the options available. I hope to see you again, adventurer.')