print('Please enter the following:')
print('')
adjective = input('Adjective: ')
animal = input('Animal: ')
verb1 = input('Verb: ')
exclamation = input('Exclamation: ')
verb2 = input('Verb: ')
verb3 = input('Verb: ')
animal2 = input('Animal: ')
verb4 = input('Verb: ')
adjective2 = input('Adjective: ')
print('')
print('Your story is: ')
print('')
print('The other day, I was really in trouble. It all started when I saw a very ')  
print(adjective + ' ' + animal + ' ' + verb1 + ' down the hallway. "' + exclamation.capitalize() + '!" I yelled. But all')
print('I could think to do was to ' + verb2 + ' over and over. Miraculously,')
print('that caused it to stop, but not before it tried to ' + verb3)
#have to use double quotes the next line for "That's"
print("right in front of my family. That's when I saw it. I saw the")
print(adjective2 + ' ' + animal2 + ' coming our way. I quickly picked up the ' + animal)
print('so we could get out of the way of the ' + animal2 + ' when it')
print('started to ' + verb4 + ' at us. Luckily we got away')
print('from the ' + adjective2 + ' ' + animal2 + ' before it ran into us!')
print('')
print('The end!')
